eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8005
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-RIBBON