server:
  port: 8888
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangyuyi/springcloud/
          search-paths: config
      label: master
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false